In [1]:
from vi_and_pi import *
from vi_and_pi import value_iteration as value_iteration_test
from vi_and_pi import policy_iteration as policy_iteration_test
from lake_envs import *
import gym

# Value Iteration

In [2]:
env_d = gym.make("Deterministic-4x4-FrozenLake-v0")
env_s = gym.make("Stochastic-4x4-FrozenLake-v0")

/home/tovitu/miniconda3/envs/ml/lib/python3.10/site-packages/gym/envs/registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)


## Deterministic Case

In [3]:
V_pi, p_pi = value_iteration(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)

Value iteration converged in 7 iterations


In [4]:
p_pi

array([1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0])

## Stochastic Case

In [5]:
V_pi, p_pi = value_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)

Value iteration converged in 27 iterations


In [6]:
p_pi

array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])

# Policy Iteration

## Deterministic Case

In [7]:
V_pi, p_pi = policy_iteration(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)

Policy evaluation converged in 1 iterations
Policy evaluation converged in 2 iterations
Policy evaluation converged in 3 iterations
Policy evaluation converged in 4 iterations
Policy evaluation converged in 6 iterations
Policy evaluation converged in 6 iterations
Policy evaluation converged in 7 iterations


In [8]:
p_pi

array([1, 2, 1, 0, 1, 0, 1, 0, 2, 1, 1, 0, 0, 2, 2, 0])

## Stochastic Case

In [9]:
V_pi, p_pi = policy_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)

Policy evaluation converged in 1 iterations
Policy evaluation converged in 9 iterations
Policy evaluation converged in 19 iterations
Policy evaluation converged in 21 iterations
Policy evaluation converged in 27 iterations
Policy evaluation converged in 27 iterations


In [10]:
p_pi

array([0, 3, 0, 3, 0, 0, 0, 0, 3, 1, 0, 0, 0, 2, 1, 0])

In [11]:
#END

# Test Section

In [16]:
V_pi, p_pi = value_iteration(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)
V_pi_test, p_pi_test = value_iteration_test(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)
assert np.allclose(V_pi, V_pi_test) and np.all(p_pi == p_pi_test)

Value iteration converged in 7 iterations
Value iteration converged in 7 iterations


In [18]:
V_pi, p_pi = value_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
V_pi_test, p_pi_test = value_iteration_test(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
assert np.allclose(V_pi, V_pi_test) and np.all(p_pi == p_pi_test)

Value iteration converged in 27 iterations
Value iteration converged in 27 iterations


In [19]:
V_pi, p_pi = policy_iteration(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)
V_pi_test, p_pi_test = policy_iteration_test(env_d.P, env_d.nS, env_d.nA, gamma=0.9, tol=1e-3)
assert np.allclose(V_pi, V_pi_test) and np.all(p_pi == p_pi_test)

Policy evaluation converged in 1 iterations
Policy evaluation converged in 2 iterations
Policy evaluation converged in 3 iterations
Policy evaluation converged in 4 iterations
Policy evaluation converged in 6 iterations
Policy evaluation converged in 6 iterations
Policy evaluation converged in 7 iterations
Policy evaluation converged in 1 iterations
Policy evaluation converged in 2 iterations
Policy evaluation converged in 3 iterations
Policy evaluation converged in 4 iterations
Policy evaluation converged in 6 iterations
Policy evaluation converged in 6 iterations
Policy evaluation converged in 7 iterations


In [20]:
V_pi, p_pi = policy_iteration(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
V_pi_test, p_pi_test = policy_iteration_test(env_s.P, env_s.nS, env_s.nA, gamma=0.9, tol=1e-3)
assert np.allclose(V_pi, V_pi_test) and np.all(p_pi == p_pi_test)

Policy evaluation converged in 1 iterations
Policy evaluation converged in 9 iterations
Policy evaluation converged in 19 iterations
Policy evaluation converged in 21 iterations
Policy evaluation converged in 27 iterations
Policy evaluation converged in 27 iterations
Policy evaluation converged in 1 iterations
Policy evaluation converged in 9 iterations
Policy evaluation converged in 19 iterations
Policy evaluation converged in 21 iterations
Policy evaluation converged in 27 iterations
Policy evaluation converged in 27 iterations
